// ═══════════════════════════════════════════════════════════════════
// LaTeX Compiler — Local TeX Live / MiKTeX compilation
// ═══════════════════════════════════════════════════════════════════
// Since Overleaf has no public compilation API, this uses local
// TeX distribution for PDF generation.

import { exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs/promises";
import * as path from "path";

const execAsync = promisify(exec);

/**
 * Compiles a LaTeX file to PDF using the local TeX distribution.
 */
export async function compileLatex(
  texFilePath: string,
  outputDir?: string,
): Promise<{
  success: boolean;
  pdfPath?: string;
  error?: string;
  log?: string;
}> {
  const latexBin = process.env.LATEX_BIN_PATH || "";

  // Determine compiler command
  const compilers = [
    path.join(latexBin, "pdflatex"),
    path.join(latexBin, "xelatex"),
    path.join(latexBin, "lualatex"),
    "pdflatex",
    "xelatex",
    "lualatex",
  ];

  let compiler: string | null = null;

  for (const cmd of compilers) {
    try {
      await execAsync(`${cmd} --version`);
      compiler = cmd;
      break;
    } catch {
      continue;
    }
  }

  if (!compiler) {
    return {
      success: false,
      error: "No LaTeX compiler found. Install TeX Live or MiKTeX, or set LATEX_BIN_PATH in .env",
    };
  }

  const texDir = path.dirname(texFilePath);
  const texFile = path.basename(texFilePath);
  const outDir = outputDir || texDir;
  const pdfName = texFile.replace(/\.tex$/, ".pdf");
  const pdfPath = path.join(outDir, pdfName);

  try {
    // Run twice for cross-references
    const cmd = `${compiler} -interaction=nonstopmode -output-directory="${outDir}" "${texFilePath}"`;

    const { stdout: log1 } = await execAsync(cmd, {
      cwd: texDir,
      timeout: 60000,
    });

    // Second pass
    const { stdout: log2 } = await execAsync(cmd, {
      cwd: texDir,
      timeout: 60000,
    });

    // Check if PDF was generated
    try {
      await fs.access(pdfPath);
      return {
        success: true,
        pdfPath,
        log: log2.slice(-500), // Last 500 chars of log
      };
    } catch {
      return {
        success: false,
        error: "Compilation ran but PDF was not generated",
        log: log2.slice(-1000),
      };
    }
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    return {
      success: false,
      error: `LaTeX compilation failed: ${errMsg}`,
      log: errMsg.slice(-1000),
    };
  }
}

/**
 * Checks if a LaTeX compiler is available.
 */
export async function isLatexAvailable(): Promise<{
  available: boolean;
  compiler?: string;
  version?: string;
}> {
  const compilers = ["pdflatex", "xelatex", "lualatex"];
  const latexBin = process.env.LATEX_BIN_PATH;

  if (latexBin) {
    compilers.unshift(
      path.join(latexBin, "pdflatex"),
      path.join(latexBin, "xelatex"),
      path.join(latexBin, "lualatex"),
    );
  }

  for (const cmd of compilers) {
    try {
      const { stdout } = await execAsync(`${cmd} --version`);
      const firstLine = stdout.split("\n")[0];
      return {
        available: true,
        compiler: cmd,
        version: firstLine.trim(),
      };
    } catch {
      continue;
    }
  }

  return { available: false };
}

/**
 * Cleans up auxiliary files generated by LaTeX compilation.
 */
export async function cleanupAuxFiles(texFilePath: string): Promise<void> {
  const dir = path.dirname(texFilePath);
  const base = path.basename(texFilePath, ".tex");

  const auxExtensions = [".aux", ".log", ".out", ".toc", ".lof", ".lot", ".fls", ".fdb_latexmk", ".synctex.gz"];

  for (const ext of auxExtensions) {
    try {
      await fs.unlink(path.join(dir, base + ext));
    } catch {
      // File doesn't exist, that's fine
    }
  }
}
